Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace OnlineStoreForJewellery.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [DisplayName("Display Order")]
        [Range(1, 100, ErrorMessage = "Display Order must be between 1 and 100 only!!")]
        public int DisplayOrder { get; set; }
        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
    }
}

Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization; 
using OnlineStoreForJewellery.Models;
using OnlineStoreForJewellery.Utility;
using OnlineStoreForJewellery.Repository.IRepository;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineStoreForJewellery.Controllers
{
   
    [Authorize]
    public class ItemController : Controller
    {
        
        private readonly IUnitOfWork _unitOfWork;

        public ItemController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Item> objItemList = _unitOfWork.Item.GetAll();
            return View(objItemList);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name.");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Item.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Item created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);
            var itemFromDbFirst = _unitOfWork.Item.GetFirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (itemFromDbFirst == null)
            {
                return NotFound();
            }

            return View(itemFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Item obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name.");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Item.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Item updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);
            var itemFromDbFirst = _unitOfWork.Item.GetFirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (itemFromDbFirst == null)
            {
                return NotFound();
            }

            return View(itemFromDbFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.Item.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Item.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Item deleted successfully";
            return RedirectToAction("Index");
        }
        
    }
}

Views/Item/Create.cshtml
@model Item
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <form method="post">
        <div class="border p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-dark">Create Category</h2>
                <hr />
            </div>
            @*<div asp-validation-summary="All"></div>*@
            <div class="mb-3">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="DisplayOrder"></label>
                <input asp-for="DisplayOrder" class="form-control" />
                <span asp-validation-for="DisplayOrder" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary" style="width:150px; background-color: #87413f ">Create</button>
            <a asp-area="Admin" asp-controller="Item" asp-action="Index" class="btn btn-secondary" style="width:150px">
                Back to List
            </a>
        </div>
    </form>

    @section Scripts{
        @{
            <partial name="_ValidationScriptsPartial" />
        }
    }

Views/Item/Delete.cshtml
@model Item
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <form method="post" asp-action="Delete">
        <input asp-for="Id" hidden />
        <div class="border p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-dark">Delete Item</h2>
                <hr />
            </div>
            @*<div asp-validation-summary="All"></div>*@
            <div class="mb-3">
                <label asp-for="Name"></label>
                <input asp-for="Name" disabled class="form-control" />
            </div>
            <div class="mb-3">
                <label asp-for="DisplayOrder"></label>
                <input asp-for="DisplayOrder" disabled class="form-control" />
            </div>
            <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
            <a asp-area="Admin" asp-controller="Item" asp-action="Index" class="btn btn-secondary" style="width:150px">
                Back to List
            </a>
        </div>
    </form>

    @section Scripts{
        @{
            <partial name="_ValidationScriptsPartial" />
        }
    }

Views/Item/Edit.cshtml
@model Item
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <form method="post" asp-action="Edit">
        <div class="border p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-dark">Edit Item</h2>
                <hr />
            </div>
            @*<div asp-validation-summary="All"></div>*@
            <div class="mb-3">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="DisplayOrder"></label>
                <input asp-for="DisplayOrder" class="form-control" />
                <span asp-validation-for="DisplayOrder" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary" style="width:150px; background-color: #87413f ">Update</button>
            <a asp-area="Admin" asp-controller="Item" asp-action="Index" class="btn btn-secondary" style="width:150px">
                Back to List
            </a>
        </div>
    </form>

    @section Scripts{
        @{
            <partial name="_ValidationScriptsPartial" />
        }
    }

Views/Item/Index.cshtml
@model IEnumerable<Item>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-dark mb-0" style="color: #87413f ">Item List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-area="" asp-controller="Item" asp-action="Create" class="btn btn-outline-accent text-white d-block w-100 mt-4" style="background-color: #87413f ">
                <i class="fa fa-plus"></i> &nbsp; Create New Item
            </a>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Item Name
                </th>
                <th>
                    Display Order
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">
                        @obj.Name
                    </td>
                    <td width="30%">
                        @obj.DisplayOrder
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Item" asp-action="Edit" asp-route-id="@obj.Id"
                               class="btn btn-primary mx-2"> <i class="fa fa-pencil-square"></i> Edit</a>
                            <a asp-controller="Item" asp-action="Delete" asp-route-id="@obj.Id"
                               class="btn btn-danger mx-2"> <i class="fa fa-trash"></i> Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>